#!/bin/bash
SELENIUM_DIR="misc"
if [ \! -f "$SELENIUM_DIR/selenium-server-standalone-2.26.0.jar" ]; then 
    (cd "$SELENIUM_DIR" && wget "http://selenium.googlecode.com/files/selenium-server-standalone-2.26.0.jar")
fi

if [ -f "$SELENIUM_DIR/chromedriver" ]; then
  java -jar "$SELENIUM_DIR/selenium-server-standalone-2.26.0.jar"  -Dwebdriver.chrome.driver="$SELENIUM_DIR/chromedriver"  -Dwebdriver.chrome.switches="--disable-web-security" 
else 
  echo "!!! Starting without chromedriver support, 
!!! for google-chrome browser support go to http://code.google.com/p/chromedriver/, 
!!! download release and put chromedriver into misc/ directory. 
!!! After that restart $0"
  java -jar "$SELENIUM_DIR/selenium-server-standalone-2.26.0.jar"
fi
